services:
  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    networks:
      default:
        aliases:
          - api-nginx
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      default:
        aliases:
          - api-postgres
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      default:
        aliases:
          - api-redis
    volumes:
      - redis-data:/data

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    networks:
      default:
        aliases:
          - api-php
    depends_on:
      - postgres
      - redis
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE="dbname"
      - DB_USERNAME="dbuser"
      - DB_PASSWORD="dbpassword"
    volumes:
      - .:/var/www/html

volumes:
  postgres-data:
  redis-data: